name: python-test
services:
    api:
        container_name: script-pencatat-keuangan
        hostname: script-pencatat-keuangan
        image: ghcr.io/rahmadwidiansyah/script_pencatat_keuangan:v1.3
        networks:
            default: null
        ports:
            - mode: ingress
              target: 3987
              published: "3987"
              protocol: tcp
        restart: unless-stopped
networks:
    default:
        name: python-test_default
